spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projetoIntegradorIII?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: M_th__s03!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    properties:
      #javax:
        #persistence:
          #schema-generation:
            #scripts:
              #action: create
              #create-target: src/main/resources/ddl.sql
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/testdata
  web:
    resources:
      add-mappings: false